### ISSUE TITLE
Create documentation from discussion items in #11

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/porTools#17]
Create documentation (as noted in [this comment](https://github.com/Sage-Bionetworks/porTools/issues/11#issuecomment-1151235972)) as part of product planning as this feature will likely be of interest to many other groups. 

AC: Information from ticket #11 distilled into a Google Doc that can be shared with a broader audience.

**Comment by milen-sage** [comment]
This is related to #12.
