### ISSUE TITLE
AD pub table won't update

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/porTools#7]
I believe the problem is related to the pubmed query in this script: https://github.com/Sage-Bionetworks/porTools/blob/master/inst/scripts/update-publications-ad.R.

The table update has failed since September, so I don't think it's related to the recent python client updates.

Here's the code I'm running locally, using my cached synapse credentials (didn't provide an auth token argument):

`Rscript update-publications-ad.R --grant_table syn17024229 --parent syn20463015 --pub_table syn20448807`

Here's the error returned:

```
[####################]100.00%   1/1   Done...
Downloading  [####################]100.00%   2.6kB/2.6kB (847.4kB/s) SYNAPSE_TABLE_QUERY_84503083.csv Done...
    Killing the request! Something is not working. Please, try again later
Error in if (class(pubmedArticle) != "character" | regexpr("(<PubmedArticle)(.+)(\\/PubmedArticle>)",  : 
  argument is of length zero
Calls: query_list_general ... query_list_pmids -> <Anonymous> -> .f -> query_pm -> <Anonymous>
Execution halted
```

**Comment by thomasyu888** [comment]
@avanlinden Hey, how would you like us to assist you with updating this script?  I personally have no knowledge of how this code is written, but am happy to walk through the code with you.

**Comment by avanlinden** [comment]
@thomasyu888 I have a little bit of time this week to dive back into this. Since the problem is likely with the pubmed query I'll ask in slack if anyone has any experience with the R PubMed package or the PubMed API more generally and see if I can get any thoughts on how to proceed. Thanks for checking in.

**Comment by thomasyu888** [comment]
@avanlinden .  I took a deeper dive and the function that is failing is `easyPubMed::article_to_df`.  Specifically, when `text_blob` is an empty vector or list.

```
query_pm <- function(pmid, sleep_time = 0.35) {
  structured_pmid_query <- easyPubMed::get_pubmed_ids(pmid)
  text_blob <- easyPubMed::fetch_pubmed_data(structured_pmid_query)
  df <- easyPubMed::article_to_df(text_blob)
  if (is.null(df)){
    df <- easyPubMed::article_to_df(text_blob, getAuthors = FALSE)
  }
  # Add a wait to get around rate limiting of 3 requests/sec
  Sys.sleep(sleep_time)
  df
}
```

```
> easyPubMed::article_to_df(c(), getAuthors = FALSE)
Error in if (class(pubmedArticle) != "character" | regexpr("(<PubmedArticle)(.+)(\\/PubmedArticle>)",  : 
  argument is of length zero
```

**Comment by thomasyu888** [comment]
I ran the code @avanlinden and it seems to run now?  Did something change in the grant table?

**Comment by thomasyu888** [comment]
@avanlinden Did something change in the past 9 days?  The code seems to be able to run now.  Can you try to re-run one of the github actions?

**Comment by avanlinden** [comment]
@thomasyu888 Yeah the error behavior is unpredictable. Sometimes it fails because of the empty text_blob from the pubmed query, sometimes it fails because of a specific record that contains a Finnish author name with an umlaut that gets converted to a " and freaks out Synapse (have tried to fix this but it's still not catching it), and sometimes it works. I can't reliably predict which error behavior I'll get. 

Maybe running it in a service catalog instance has something to do with it...I'll try to re-run one of the github actions this morning. If it works it works! (thank you for your help on this, I had some time sensitive curation stuff pop up last week and did not get to dig as much as I wanted).

**Comment by avanlinden** [comment]
@thomasyu888 Did the code complete when you ran it in the SC instance? I see that various publication entities in [this folder](https://www.synapse.org/#!Synapse:syn20463015) were successfully updated by you, but the [file view](https://www.synapse.org/#!Synapse:syn20448807/tables/) that is scoped to that folder and drives the publication records in the portal hasn't updated since October.

**Comment by thomasyu888** [comment]
@avanlinden The code did complete!

**Comment by avanlinden** [comment]
That's aggravating! Even when it works it somehow doesn't work. I know CSCB uses [this pubmed crawler](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/main/python/pubmed_crawler.py) to get publications, do you think it would be easier long term to try to use a version of that script for AD?

**Comment by avanlinden** [comment]
@thomasyu888 testing a solution for cases when the pmid returns nothing, I'll let you know if it works (fingers crossed).

**Comment by thomasyu888** [comment]
Ah interesting - I think I need to have a better understanding of this package.  If its only purpose is to be a pubmed crawler, we should try to converge on our solutions and only maintain one package.

Thanks - let me know how testing goes.

**Comment by avanlinden** [comment]
@thomasyu888 I think the calls that easyPubMedR makes to the PubMed API are just inherently unstable. I used `safely` and `tryCatch` to try to isolate a case where the `article_to_df` function was returning an empty text blob, but could not identify a PubMed ID that was consistently causing an error. Running the full script with `safely` around that function just made the line before it `fetch_pubmed_data` return an empty object. Running _that_ safely just made the first call `get_pubmed_ids` return an empty object. Running them all safely made the functions print "Killing the request! Something is not working!" multiple times without actually killing the request. 

Then I ran the whole script in an ec2 instance and the table updated just fine, even though it printed nothing and took over 8 hours for the code to complete.

All this to say, I think the `easyPubMed` package is difficult to work with. There is also something wrong with the way we're parsing the returned XML text from PubMed because the year annotations on the publication entities do not match the actual publication dates (e.g., a file will get annotated with 2021 but if you follow the link to the journal page, it was published in 2018). 

A better option might be to use the Bio.Entrez python module to query PubMed, as I think it is better supported and documented. We could use it with reticulate in this existing script, or scrap this altogether and use some or all of the [CBSC python PubMed crawler](https://github.com/Sage-Bionetworks/csbc-pson-dcc/blob/main/python/pubmed_crawler.py) to do what we need here. That would let us build something more robust, and fix the publication year mismatch issue. It would not necessarily need to be part of this porTools package. 

Thanks for you help and let me know what you think!

**Comment by thomasyu888** [comment]
No problem @avanlinden - I think we can try to use the CSBS python public crawler - it would be wasteful to duplicate efforts that have already been done.  We might be able to identify things that need to be added or modified that could be PR's into the module.

**Comment by avanlinden** [comment]
Closing this for now as more substantial changes to the script are warranted.
